---

- hosts: databases

  vars:
          db_name: mantis
          db_user: autom
          db_psswrd: autom
          paquets:
                  - python3-pip
                  - postgresql
                  - postgresql-contrib
                  - libpq-dev
                  - python3-psycopg2

  tasks:
          - name: Maj des paquets
            apt:
                    update_cache: yes
                    upgrade: yes

          - name: Installation des paquets
            apt:
                    name: "{{ item }}"
                    state: present
            loop: "{{ paquets }}"
            notify: Démarrer postgresql

          - name: Création BDD
            postgresql_db:
                    name: "{{ db_name }}"
                    state: present
            become_user: postgres

          - name: Création utilisateur BDD
            postgresql_user:
                    name: "{{ db_user }}"
                    password: "{{ db_psswrd }}"
                    priv: ALL
                    state: present
            become_user: postgres

  handlers:
          - name: Démarrer postgresql
            service:
                    name: postgresql
                    state: started
