---

- hosts: reverse_proxy

  tasks:
          - name: Charger les variables
            include_vars:
                    file: vars.yml

          - name: fix apt
            shell: apt -y --fix-broken install

          - name: Maj des paquets
            apt:
                    update_cache: yes
                    upgrade: yes

          - name: Installation Nginx
            apt:
                    name: nginx
                    state: present
            notify: Unlink default

          - name: Copier fichier de conf
            copy:
                    src: reverse-proxy.conf.j2
                    dest: /etc/nginx/sites-available/reverse-proxy.conf

          - name: Créer un lien symbolique
            file:
                    src: /etc/nginx/sites-available/reverse-proxy.conf
                    dest: /etc/nginx/sites-enabled/reverse-proxy.conf
                    state: link

          - name: Créer VirtualHost
            template:
                    src: mantisbt.conf.j2
                    dest: /etc/nginx/sites-available/mantisbt.conf
            #notify: Lancer Nginx

          - name: Lancer Nginx
            service:
                    name: nginx
                    state: started

  handlers:
          - name: Unlink default
            shell: unlink /etc/nginx/sites-enabled/default

          - name: Lancer Nginx
            service:
                    name: nginx
                    state: started