---

- hosts: mantis_db

  tasks:
          - name: Charger les variables
            include_vars:
                    file: vars.yml

          - name: Exporter la BDD dans un fichier
            postgresql_db:
                    name: "{{ db_name }}"
                    state: dump
                    target: ~/mantis_db_backup.sql
            become: true
            become_user: postgres

          - name: Import test
            postgresql_db:
                    name: "{{ db_name }}"
                    state: restore
                    target: ~/mantis_db_backup.sql
            become: true
            become_user: postgres

          - name: Copier le fichier sur le serveur backup
            synchronize:
                    mode: push
                    src: ~/mantis_db_backup.sql
                    dest: ~/mantis_db_backup.sql
            delegate_to: mantis_db_backup

- hosts: mantis_db_backup

  tasks:
          - name: Importer la BDD depuis le fichier
            postgresql_db:
                    name: "{{ db_name }}"
                    state: restore
                    target: ~/mantis_db_backup.sql
            become: true
            become_user: postgres
