---

- hosts: mantis_db

  tasks:
          - name: Charger les variables
            include_vars:
                    file: vars.yml

          - name: Exporter la BDD dans un fichier
            postgresql_db:
                    name: "{{ db_name }}"
                    state: dump
                    target: ~/mantis_db_backup.sql
            become: true
            become_user: postgres

          - name: Copier le fichier sur le controleur
            fetch:
                    src: ~/mantis_db_backup.sql
                    dest: ~/DB_backup/mantis_db_backup.sql

