---

- hosts: mantis_db
  gather_facts: false

  tasks:
    - name: Charger les variables
      include_vars:
        file: vars.yml

    - name: Exporter la BDD dans un fichier
      postgresql_db:
        name: "{{ db_name }}"
        state: dump
        target: /tmp/mantis_db_backup.sql
      become: true
      become_user: postgres

    - name: Copier le fichier sur le controleur
      fetch:
        src: /tmp/mantis_db_backup.sql
        dest: /tmp/

- hosts: mantis_db_backup
  gather_facts: false

  tasks:
    - name: Charger les variables
      include_vars:
        file: vars.yml

    - name: Copier le fichier sur le host
      copy:
        src: /tmp/mantis_db/tmp/mantis_db_backup.sql
        dest: /tmp/mantis_db_backup.sql

    - name: Importer la BDD depuis un fichier
      postgresql_db:
        name: "{{ db_name }}"
        state: restore
        target: /tmp/mantis_db_backup.sql
      become: true
      become_user: postgres