---

- hosts: mantis_db_backup

  tasks:
          - name: Copier le fichier sur le host
            copy:
                    src: ~/DB_backup/mantis_db_backup.sql
                    dest: ~/mantis_db_backup.sql

          - name: Importer la BDD depuis le fichier
            postgresql_db:
                    name: mantis
                    state: restore
                    target: ~/mantis_db_backup.sql
            become: true
            become_user: postgres

